alter table transactions drop constraint if exists transactions_category_check;
alter table transactions add constraint transactions_category_check check (category in ('ALIMENTACAO','TRANSPORTE','MORADIA','SAUDE','LAZER','EDUCACAO','COMPRAS','OUTROS','INVESTIMENTO','IMPOSTOS'));
alter table transactions drop constraint if exists transactions_payment_method_check;
alter table transactions add constraint transactions_payment_method_check check (payment_method in ('PIX','CARTAO_DEBITO','CARTAO_CREDITO_AVISTA','CARTAO_CREDITO_PARCELADO','DINHEIRO','TRANSFERENCIA'));
alter table wishlist_items drop constraint if exists wishlist_items_category_check;
alter table wishlist_items add constraint wishlist_items_category_check check (category in ('ALIMENTACAO','TRANSPORTE','MORADIA','SAUDE','LAZER','EDUCACAO','COMPRAS','OUTROS','INVESTIMENTO','IMPOSTOS'));
alter table wishlist_items drop constraint if exists wishlist_items_payment_method_check;
alter table wishlist_items add constraint wishlist_items_payment_method_check check (payment_method in ('PIX','CARTAO_DEBITO','CARTAO_CREDITO_AVISTA','CARTAO_CREDITO_PARCELADO','DINHEIRO','TRANSFERENCIA'));
alter table transactions add column investment_movement_id bigint unique references investment_movements(id);
alter table transactions add column managed_reference varchar(120) unique;
alter table investment_movements add column brokerage_fee numeric(19,2);
alter table investment_movements add column b3_fee numeric(19,2);
alter table investment_movements add column other_costs numeric(19,2);
alter table investment_movements add column withheld_tax numeric(19,2);
alter table investment_movements add column cost_basis numeric(19,6);
alter table investment_movements add column realized_gain numeric(19,6);
alter table investment_movements add column exchange_rate numeric(19,8);
alter table investment_movements drop constraint if exists investment_movements_movement_type_check;
alter table investment_movements add constraint investment_movements_movement_type_check check (movement_type in ('COMPRA','VENDA','APORTE','RESGATE','DIVIDENDO','RENDIMENTO','SALDO_INICIAL'));
alter table investment_positions add column tax_regime varchar(20);
alter table investment_positions add column manual_tax_rate numeric(8,4);
alter table investment_positions add column iof_applicable boolean not null default false;
alter table investment_positions add column opening_date date;
alter table investment_positions add column redeemed boolean not null default false;
