package com.controledegastos.backend.auth;

import com.controledegastos.backend.auth.dto.AuthResponseDTO;
import com.controledegastos.backend.auth.dto.LoginRequestDTO;
import com.controledegastos.backend.auth.dto.RegisterRequestDTO;
import com.controledegastos.backend.security.JwtService;
import com.controledegastos.backend.user.User;
import com.controledegastos.backend.user.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class AuthService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder; //Inject SecurityConfig
    private final JwtService jwtService;

    // Registers a new user and immediately returns the tokens — no need to log in afterward
    public AuthResponseDTO register(RegisterRequestDTO dto) {

        // Checks if the email is already in use before attempting to save
        // Throws an exception with a clear message — the controller will return 409 Conflict
        if (userRepository.existsByEmail(dto.email())) {
            throw new IllegalArgumentException("Email já cadastrado" + dto.email());
        }

        // Builds the User using the Builder generated by Lombok
        // NEVER save dto.password() directly — always hash it first
        User user = User.builder()
                .name(dto.name())
                .email(dto.email())
                .password(passwordEncoder.encode(dto.password())) // BCrypt hash
                .role(User.Role.USER) // Every registration start with the USER
                .build();

        // It persists in the database — @PrePersist automatically fills in createdAt
        userRepository.save(user);

        // Generates the two tokens and returns them to the client
        return buildAuthResponse(user);
    }

    public AuthResponseDTO login(LoginRequestDTO dto) {

        // Searches for the user by email — if not found, invalid credentials
        User user = userRepository.findByEmail(dto.email())
                .orElseThrow(() -> new BadCredentialsException("Credenciais inválidas"));

        // BCrypt compares the entered password with the hash stored in the database
        // passwordEncoder.matches() never compares plain text — it always uses the hash
        if (!passwordEncoder.matches(dto.password(), user.getPassword())) {
            throw new BadCredentialsException("Credenciais inválidas");
        }
        // Generic message on purpose — not specifying whether it was the email or the password
        // that is wrong prevents user enumeration attacks

        return buildAuthResponse(user);
    }

    // Private method reused by register and login
    // Centralizes the creation of AuthResponseDTO — DRY principle
    private AuthResponseDTO buildAuthResponse(User user) {
        return new AuthResponseDTO(
                jwtService.generateAccessToken(user),
                jwtService.generateRefreshToken(user),
                user.getName(),
                user.getEmail(),
                user.getRole().name()
        );
    }
}
